//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revit2017_Adapter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Revit2017_Adapter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L:\BH-Revit\Revit2017\Family Templates\English\Metric Structural Framing - Beams and Braces.rft.
        /// </summary>
        internal static string BeamTemplate {
            get {
                return ResourceManager.GetString("BeamTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L:\BH-Revit\Revit2017\Libraries\UK\_BH Library\BH Structures\BH Structural\Structural Framing\Steel\_Circular Hollow Sections.rfa.
        /// </summary>
        internal static string CHS {
            get {
                return ResourceManager.GetString("CHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L:\BH-Revit\Revit2017\Family Templates\English\Metric Structural Column.rft.
        /// </summary>
        internal static string ColumnTemplate {
            get {
                return ResourceManager.GetString("ColumnTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L:\BH-Revit\Revit2017\Family Templates\English\Metric Structural Framing - Complex and Trusses.rft.
        /// </summary>
        internal static string ComplexFramingTemplate {
            get {
                return ResourceManager.GetString("ComplexFramingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L:\BH-Revit\Revit2017\Family Templates\English\Metric Generic Model.rft.
        /// </summary>
        internal static string GenericTemplate {
            get {
                return ResourceManager.GetString("GenericTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L:\BH-Revit\Revit2017\Libraries\UK\_BH Library\BH Structures\BH Structural\Structural Framing\Steel\_Rectangular Hollow Sections.rfa.
        /// </summary>
        internal static string RHS {
            get {
                return ResourceManager.GetString("RHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L:\BH-Revit\Revit2017\Libraries\UK\_BH Library\BH Structures\BH Structural\Structural Framing\Steel\_SFB-Beams.rfa.
        /// </summary>
        internal static string SFB {
            get {
                return ResourceManager.GetString("SFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L:\BH-Revit\Revit2017\Libraries\UK\_BH Library\BH Structures\BH Structural\Structural Framing\Steel\_Square Hollow Sections.rfa.
        /// </summary>
        internal static string SHS {
            get {
                return ResourceManager.GetString("SHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L:\BH-Revit\Revit2017\Libraries\UK\_BH Library\BH Structures\BH Structural\Structural Framing\Steel\_T-Tees from Universal Beams.rfa.
        /// </summary>
        internal static string TUB {
            get {
                return ResourceManager.GetString("TUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L:\BH-Revit\Revit2017\Libraries\UK\_BH Library\BH Structures\BH Structural\Structural Framing\Steel\_T-Tees from Universal Columns.rfa.
        /// </summary>
        internal static string TUC {
            get {
                return ResourceManager.GetString("TUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L:\BH-Revit\Revit2017\Libraries\UK\_BH Library\BH Structures\BH Structural\Structural Framing\Steel\_UB-Universal Beams.rfa.
        /// </summary>
        internal static string UB {
            get {
                return ResourceManager.GetString("UB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L:\BH-Revit\Revit2017\Libraries\UK\_BH Library\BH Structures\BH Structural\Structural Framing\Steel\_UBP-Universal Bearing Pile.rfa.
        /// </summary>
        internal static string UBP {
            get {
                return ResourceManager.GetString("UBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L:\BH-Revit\Revit2017\Libraries\UK\_BH Library\BH Structures\BH Structural\Structural Framing\Steel\_UC-Universal Columns.rfa.
        /// </summary>
        internal static string UC {
            get {
                return ResourceManager.GetString("UC", resourceCulture);
            }
        }
    }
}
